BoxLayout:
    orientation: 'vertical'
#    orientation: 'horizontal'
    Button:
        text: 'Clear'
        on_press: app.clear_field()
    TextInput:
        id: input_name
        text: ''
        text_size: 22
        halign: 'center'
    Button:
        text: 'Greet'
        on_press: app.handle_greet()
    Label:
        id: output_label
        text: 'Enter your name'
        color: (1, 1, 0, 1)